---
# Only some default modules are confgured here.
# Additional modules can found in <modulename>.yml
- name: Configure Modules 00-base.conf
  template:
    src: 00-base.conf.j2
    dest: /etc/httpd/conf.modules.d/00-base.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart httpd
