---
# task/mod_ssl.yml for httpd
- name: "Set mod_ssl to {{ wtd_httpd_mod_ssl_state }}"
  package:
    name: "{{ item }}"
    state: "{{ wtd_httpd_mod_ssl_state }}"
  with_items: "{{ wtd_httpd_mod_ssl_packages }}"
  notify: Restart httpd
  tags:
    - httpd
    - security

- name: "Configure mod_ssl with {{ wtd_httpd_mod_ssl_config }}"
  template:
    src: "ssl_{{ wtd_httpd_mod_ssl_config }}.conf.j2"
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart httpd
  tags:
    - httpd
    - security
